# Generated by Django 3.2.15 on 2022-10-13 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dom', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('no_ext', models.CharField(blank=True, max_length=50, null=True)),
                ('no_int', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('Indicaciones', models.TextField(blank=True, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=150, null=True)),
                ('zip_code', models.CharField(max_length=100)),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_codigo', models.CharField(max_length=128)),
                ('d_asenta', models.CharField(max_length=128)),
                ('d_tipo_asenta', models.CharField(max_length=128)),
                ('d_mnpio', models.CharField(max_length=128)),
                ('d_estado', models.CharField(max_length=128)),
                ('d_ciudad', models.CharField(blank=True, max_length=128, null=True)),
                ('d_cp', models.CharField(blank=True, max_length=128, null=True)),
                ('c_estado', models.CharField(max_length=128)),
                ('c_oficina', models.CharField(max_length=128)),
                ('c_cp', models.CharField(blank=True, max_length=128, null=True)),
                ('c_tipo_asenta', models.CharField(max_length=128)),
                ('c_mnpio', models.CharField(max_length=128)),
                ('id_asenta_cpcons', models.CharField(max_length=128)),
                ('d_zona', models.CharField(max_length=128)),
                ('c_cve_ciudad', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ColourVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='cart.address')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='cart.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SizeVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='product_images')),
                ('descritption', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('available_colours', models.ManyToManyField(to='cart.ColourVariation')),
                ('available_sizes', models.ManyToManyField(to='cart.SizeVariation')),
                ('primary_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_products', to='cart.category')),
                ('secondary_categories', models.ManyToManyField(blank=True, to='cart.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Paypal', 'Paypal')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('succesful', models.BooleanField(default=False)),
                ('amount', models.FloatField()),
                ('raw_response', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cart.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.colourvariation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sizevariation')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='mnpiociu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.addresses'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
